Celery and test update for CircleCI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -29,60 +29,57 @@ jobs:
           # Install dependencies with --user to enable easier caching
           name: Install dependencies
           command: |
-            python3 -m venv climmob_env
-            source climmob_env/bin/activate
-            pip install -r requirements.txt
-            pip install setuptools
+            pip install -r requirements.txt --user
+            pip install codecov --user
+            /home/circleci/.local/bin/codecov
             mysql -h 127.0.0.1 -u root --ssl-mode=DISABLED --password=circleci --execute='CREATE SCHEMA IF NOT EXISTS climmobv4'
             mysql -h 127.0.0.1 -u root --ssl-mode=DISABLED --password=circleci climmobv4 < ./docker_files/climmob/docker_files/base_db.sql
-            python3 create_config.py --daemon --capture_output --mysql_host 127.0.0.1 --mysql_user_name root --mysql_user_password circleci --repository_path /opt/climmob_repository --odktools_path /opt/odktools --climmob_host localhost --climmob_port 5900 --forwarded_allow_ip localhost --pid_file /opt/climmob_gunicorn/climmob.pid --error_log_file /opt/climmob_log/error_log development.ini
+            python3 create_config.py --daemon --capture_output --mysql_host 127.0.0.1 --mysql_user_name root --mysql_user_password circleci --repository_path /opt/climmob_repository --odktools_path /opt/odktools --climmob_host localhost --climmob_port 5900 --forwarded_allow_ip localhost --pid_file /opt/climmob_gunicorn/climmob.pid --error_log_file /opt/climmob_log/error_log /opt/climmob_config/development.ini
+            ln -s /opt/climmob_config/development.ini ./development.ini
             python3 configure_celery.py ./development.ini
             python3 download_nltk_packages.py
-            python3 setup.py install
+            python3 setup.py install --user
             python3 setup.py compile_catalog
-            disable_ssl ./development.ini
-            configure_alembic ./development.ini .
-            configure_mysql ./development.ini .
-            configure_tests ./development.ini .
-            alembic upgrade head
-
+            /home/circleci/.local/bin/disable_ssl ./development.ini
+            /home/circleci/.local/bin/configure_alembic ./development.ini .
+            /home/circleci/.local/bin/configure_mysql ./development.ini .
+            /home/circleci/.local/bin/configure_tests ./development.ini .
+            /home/circleci/.local/bin/alembic upgrade head
       - run:
           name: Test code is well formatted
           command: |
-            source climmob_env/bin/activate
-            black --version
-            black climmob --check || exit;
-            
-#      - run:
-#          name: Run Celery in the background
-#          command: |
-#            export COLUMNS=80
-#            export CLIMMOB_PYTEST_RUNNING=true
-#            /home/circleci/.local/bin/celery -A climmob.config.celery_app worker --loglevel=info -Q ClimMob
-#          background: true
-#      - run:
-#          name: Run tests
-#          command: |
-#            export CLIMMOB_PYTEST_RUNNING=true
-#            /home/circleci/.local/bin/pytest -s --cov=climmob
-#      - run:
-#          name: upload coverage report
-#          command: |
-#            /home/circleci/.local/bin/coverage xml
-#            (/home/circleci/.local/bin/codecov --required -X search gcov pycov -f coverage.xml) || echo 'Codecov failed to upload'
-#      - run:
-#          name: Building artifacts
-#          command: |
-#            python3 setup.py sdist
-#            python3 setup.py bdist_wheel
-#      - store_artifacts:
-#          path: dist/
-#          destination: ./
-#      - save_cache:
-#          key: requirements-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "requirements.txt" }}
-#          paths:
-#            - /home/circleci/.local/lib
-#            - /home/circleci/.local/bin
+            /home/circleci/.local/bin/black --version
+            /home/circleci/.local/bin/black climmob --check || exit;
+      - run:
+          name: Run Celery in the background
+          command: |
+            export COLUMNS=80
+            export CLIMMOB_PYTEST_RUNNING=true
+            /home/circleci/.local/bin/celery -A climmob.config.celery_app worker --loglevel=info -Q ClimMob
+          background: true
+      - run:
+          name: Run tests
+          command: |
+            export CLIMMOB_PYTEST_RUNNING=true
+            /home/circleci/.local/bin/pytest -s --cov=climmob
+      - run:
+          name: upload coverage report
+          command: |
+            /home/circleci/.local/bin/coverage xml
+            (/home/circleci/.local/bin/codecov --required -X search gcov pycov -f coverage.xml) || echo 'Codecov failed to upload'
+      - run:
+          name: Building artifacts
+          command: |
+            python3 setup.py sdist
+            python3 setup.py bdist_wheel
+      - store_artifacts:
+          path: dist/
+          destination: ./
+      - save_cache:
+          key: requirements-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "requirements.txt" }}
+          paths:
+            - /home/circleci/.local/lib
+            - /home/circleci/.local/bin
 
   build_develop: &build-template
     docker:
@@ -138,6 +135,7 @@ jobs:
             configure_mysql ./development.ini .
             configure_tests ./development.ini .
             alembic upgrade head
+            ls -la
 
       - run:
           name: Test code is well formatted
@@ -146,18 +144,22 @@ jobs:
             black --version
             black climmob --check || exit;
 
-#      - run:
-#          name: Run Celery in the background
-#          command: |
-#            export COLUMNS=80
-#            export CLIMMOB_PYTEST_RUNNING=true
-#            /home/circleci/.local/bin/celery -A climmob.config.celery_app worker --loglevel=info -Q ClimMob
-#          background: true
-#      - run:
-#          name: Run tests
-#          command: |
-#            export CLIMMOB_PYTEST_RUNNING=true
-#            /home/circleci/.local/bin/pytest -s --cov=climmob
+      - run:
+          name: Run Celery in the background
+          command: |
+            source climmob_env/bin/activate
+            export COLUMNS=80
+            export CLIMMOB_PYTEST_RUNNING=true
+            celery -A climmob.config.celery_app worker --loglevel=info -Q ClimMob
+          background: true
+
+      - run:
+          name: Run tests
+          command: |
+            source climmob_env/bin/activate
+            export CLIMMOB_PYTEST_RUNNING=true
+            pytest -s --cov=climmob
+
 #      - run:
 #          name: upload coverage report
 #          command: |
